#!/usr/bin/with-contenv bash
# ==============================================================================
# Community Hass.io Add-ons: Shinobi
# Runs Shinobi
# ==============================================================================
# shellcheck disable=SC1091
source /usr/lib/hassio-addons/base.sh

# Change working directory
cd /opt/shinobi || hass.die 'Unable to change working directory'

# Run Shinobi
exec node camera.js
